### PR TITLE
Code Review for JOSS prep

### PR DESCRIPTION
**Pull request by crvernon**
**Purpose**:  Code review for JOSS submission and formal release

**Comments**:

- There were missing dependencies in the package requirements; I fixed these.
- The data version URLs dictionary in `install_supplement.py` must be updated to account for the existing release as noted in `setup.py`.  The current version had been hard coded to `3.0.0` which does not exist.  I set this back to get the distribution version that matches the current specs (0.0.1).   Same goes for the `install_weather_forcing_sample.py` procedure.
- Look into adding a progress bar for the data download since it is so large (see https://www.alpharithms.com/progress-bars-for-python-downloads-580122/)
- Fixed `match.py:385: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.` warning.  You cannot index columns using dict notation, instead use list.
- Fixed warnings generated by using `df.append` in `data_process_pop_interp.py`.  These are invoked when calling `tell.ba_pop_interpolate()` in the quickstarter.  **PLEASE ENSURE THE OUTPUTS STILL ARE AS EXPECTED** since the new functionality renumbers the index.  I don't believe this causes any issues but please confirm.
- Fixed `data_process_pop_interp.py:161: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.` warning.
- Removed warnings exemption from quickstarter as it is no longer needed.
- Changed name of quickstarter to `tell_quickstarter.ipynb`
- Removed the unfinished `run_predictor` notebook
- I build a data file named `tell/data/balancing_authority_names.yml` and added it to the package manifest to be installed with the package.  I also built a `package_data.py` script that has functions to read this.  This is to remove the need to hardcode the `ba_name` list used throughout the code.   I made an example of how to use this in `data_process_wrf.py` in the `list_wrf_files` function by calling `ba_name = get_ba_abbreviations()`.  Note the additional import of `from .package_data import get_ba_abbreviations`
- I setup an initial test suite for you here `tell/tests`.  See comment below.

**TODO**:

- [x] In the quickstarter...need a comment above `tell.map_fips_codes(start_year, end_year,raw_data_dir, current_dir)` explaining why so many `Possible matches for unmatched county "adjuntas": from FIPS file: {}` are generated.  Also, the FIPS file names are missing in the print out (e.g., ` from FIPS file: {}`). 
- [x] Add in a notice to the user of the size of the download required for `tell.install_sample_data()` in section 1.3 because it takes a long time to download.  Here is another spot where a progress bar would come in handy.
- [x] Is it reasonable to trim down the `target_ba_list` in section 2 when running the predict function?  This takes a while and would be better if only 2 or 3 ran for the quickstarter as a demo.
- [x] Some predictive models do not output stats (see `BA: AECI`).  Why is this?  Can you communicate this via a message back to the user?
- [x] In section 3, `tell.execute_forward()` fails because I do not have file `raw_data/gcamDataTable_aggParam.csv`.  Has this been left out of the data archive that gets downloaded?
- [x] Because I cannot run section 3, I cannot test section 4.  Section 4 should produce each figure in its own block, this is the eye candy - or reward - for running the above.  The default for these should be to display the figures and not save them.
- [x] Note that using a type hint in a docstring (e.g., `:type <myvar>:`) is an actual Python type (e.g., int, float, str, np.ndarray, pd.DataFrame, etc.).  Please fix where these are not types like `dir`.
- [x] BA names hard coded in a list throughout the package.  Use the protocol described in the comments section to address throughout the package.  Please fill in the names of each BA that are associated with the abbreviation in the YAML file (`tell/data/balancing_authority_names.yml`).  I left a space holder in the for you to do this (e.g., `TVA:` should be `TVA: Tennessee Valley Authority`). 
- [x] Ensure proper spacing is used in between functions (2 spaces). PyCharm will let you know when this is an issue by giving you a squiggly line
- [x] Give the code in `execute_forward.py` a little breathing room by adding space between code and comments.  Do this elsewhere as needed.  Also fix docstring formatting to breath as well using the format found in `package_data.py/read_yaml()` or something similar
- [x] No need for comments above functions, docstrings to the trick
- [x] Fix docstring formatting in `mlp_predict.py`.  Also no reason to always return None.
- [x] Remove any commented out code that is not being used
- [x] Plot functions should return the plot object so that the plots may be visualized in a notebook or elsewhere and not always saved to file
- [x] I don't see any tests.  So I started these for you but they need to be added to.  I built a test for the package data script here:  `tell/tests/test_package_data.py`
- [x] I don't see any info on how to install tell.  You will have to use pip install from github since tell already exists on PyPi.  This needs to be in the readme and docs.
- [x] In the README, use Python code block to get the correct formatting like (click edit above to see the raw markdown):
```python
import tell 

result = do_something()
```

For docs (https://immm-sfa.github.io/tell):
- [x] Missing info in the docs splash page and resize of the block icons needed.  @thurber can you help them get this formatted correctly?
- [x] Link in Interactive Quckstarter broken
- [x] Missing version in index page
- [x] For the setting up a tell run, does TELL actually use a configuration file setup?? I just added the PyYAML package as a dependency, but didn't see this functionality before.
- [x] In Tutorials, the `tell quickstarter` link points to a CERF page
- [x] Missing code API.  @thurber could you get autodoc fired up for them?  Perhaps with your new deploy action?

See the reviewer checklist here from the CERF JOSS review to make sure you have everything accounted for:  https://github.com/openjournals/joss-reviews/issues/3601

### CODE REVIEW

**Review by mcgrathc — APPROVED** [review]
I am approving these commits after review in order to integrate further edits from the comments from Chris. I appreciate the time in enhancing the package through these commits!

**Comment by crvernon** [comment]
@mcgrathc @cdburley @thurber this is now ready to address

**Comment by crvernon** [comment]
Once these have been addressed / fixes made, I will gladly re-review.

**Comment by crvernon** [comment]
Also forgot to mention, in the MLP script, there are several global variables used.  This is not a good practice in a package.  Especially the hard coding of `np.random.seed(391)`.  The user should have control of the seed value and you can set the value `391` as the default.  They may not always what to reproduce under your declared seed.

**Comment by cdburley** [comment]
We've gone through Chris' checklist and made all the suggested changes. Substantial revisions and updates to the MLP modeling approach, notebooks, and data packages.

**Pull request merged**
